import os
import json

from dotenv import load_dotenv
from groq import Groq

load_dotenv()

client = Groq(
    api_key=os.environ.get("GROQ_API_KEY")
)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.join(SCRIPT_DIR, "..", "..")

SCHEMA_PATH = os.path.join(
    PROJECT_ROOT,
    "data",
    "schema",
    "bearing.json",
)

def load_schema():
    with open(SCHEMA_PATH, "r") as f:
        return json.load(f)

def build_prompt(raw_text, schema):
    schema_str = json.dumps(
        schema,
        indent=2
    )

    return f"""You are extracting structured product data from a bearing datasheet.
    Below is the target schema. For each field, return an object with:
    - "value": the extracted value (or null if not found)
    - "confidence": "high", "medium", or "low"
    - "source_snippet": the exact short text from the document that supports this value (or null if not found)
    - "source_page": the page number containing the supporting snippet (or null if not found)

    Schema:
    {schema_str}

    Document text:
    {raw_text}

    Important evidence rules:
    - The document contains explicit page markers such as "--- PAGE 3 ---".
    - Use these markers to determine "source_page".
    - Never invent a page number.
    - "source_snippet" must come from the provided document text.
    - If a value cannot be supported by the document, return null for both "source_snippet" and "source_page".
    - Do not use outside knowledge to fill missing specifications.
    - Be precise about matching each value to its correct label.
    - Do not confuse nearby but unrelated numbers. For example, net weight and carbon footprint are different values even if they appear close together in the text.

    Return ONLY valid JSON matching this structure — no explanation, no markdown formatting, just the JSON object.
    Do not generate or populate fields in the "derived" section.
    Derived fields are generated by a separate deterministic enrichment stage.
    Return only "product_id", "category", "common", and "attributes".

    Every field in "common" and "attributes" should be present, each as:
    {{"value": ..., "confidence": ..., "source_snippet": ..., "source_page": ...}}
    """


def extract_fields(raw_text):
    schema = load_schema()
    prompt = build_prompt(
        raw_text,
        schema
    )
    with open(
    os.path.join(
        PROJECT_ROOT,
        "data",
        "schema",
        "bearing_extraction.json",
        ),
        "r",
    ) as f:
        extraction_schema = json.load(f)

    response = client.chat.completions.create(
        model="openai/gpt-oss-120b",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0,
        response_format={
            "type": "json_schema",
            "json_schema": {
                "name": "bearing_extraction",
                "schema": extraction_schema,
                "strict": True,
            },
        },
    )

    raw_output = response.choices[0].message.content

    # Strip markdown fences if the model adds them anyway.
    cleaned = (
        raw_output
        .strip()
        .removeprefix("```json")
        .removeprefix("```")
        .removesuffix("```")
        .strip()
    )
    return json.loads(cleaned)


if __name__ == "__main__":
    from src.ingestion.extract_text import (
        extract_pdf_pages,
        pages_to_text,
    )
    from src.extraction.classify_category import (
        classify_category,
    )
    raw_dir = os.path.join(
        PROJECT_ROOT,
        "data",
        "raw",
    )
    output_dir = os.path.join(
        PROJECT_ROOT,
        "data",
        "extracted",
    )
    os.makedirs(
        output_dir,
        exist_ok=True,
    )

    for filename in os.listdir(raw_dir):

        if not filename.endswith(".pdf"):
            continue

        pdf_path = os.path.join(
            raw_dir,
            filename,
        )

        print(f"Processing {filename}...")

        # Preserve page boundaries for evidence tracking.
        pages = extract_pdf_pages(
            pdf_path
        )

        raw_text = pages_to_text(
            pages
        )

        classification = classify_category(
            raw_text
        )

        print(
            f"  Classified as: "
            f"{classification['category']} "
            f"({classification['confidence']}) "
            f"- {classification['reasoning']}"
        )

        if classification["category"] != "bearing":
            print(
                "  Skipping extraction — "
                "unsupported category."
            )
            continue

        result = extract_fields(
            raw_text
        )

        output_path = os.path.join(
            output_dir,
            filename.replace(
                ".pdf",
                ".json"
            ),
        )

        with open(output_path, "w") as f:
            json.dump(
                result,
                f,
                indent=2,
                ensure_ascii=False,
            )

        print(
            f"  Saved to {output_path}"
        )